config/routes.rb
Rails.application.routes.draw do
  root :to => "albums#index"
  get "/albums" => "albums#index", as: "albums"
  get "/albums/new" => "albums#new", as: "new_album"
  get "/albums/:id" => "albums#show", as: "album"
  post "/albums" => "albums#create"
end

app/models/album.rb
class Album < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  def index
    @albums = Album.all
  end
  def show
    @album = Album.find(params[:id])
  end
  def new
    @album = Album.new
  end
  def create
    Album.create(album_params)
    redirect_to("/albums")
  end
  
  private
  def album_params
    params.require(:album).permit(:title, :artist, :year, :cover_art, :song_count)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/albums/index.html.erb
<h1>Rock 'n Rails!</h1>

<% @albums.each do |album| %>
  <p>Title: <%= album.title %></p>
  <p>Artist: <%= album.artist %></p>
  <%= image_tag album.cover_art %>
  <br>
  <%= link_to "Show Page", album_path(album.id) %>
<% end %>

app/views/albums/new.html.erb
<%= form_for @album do |f| %>
  <span>Title: </span>
  <%= f.text_field :title, required: true %><br>
  <span>Artist: </span>
  <%= f.text_field :artist, required: true %><br>
  <span>Year: </span>
  <%= f.number_field :year, required: true %><br>
  <span>Cover art: </span>
  <%= f.url_field :cover_art, required: true %><br>
  <span>Song count:</span>
  <%= f.number_field :song_count, required: true %>
  <%= f.submit %>
<% end %>

app/views/albums/show.html.erb
<h1>Rock 'n Rails</h1>

<%= image_tag @album.cover_art %>
<h1><%= @album.title %></h1>
<h2>by <%= @album.artist %></h2>
<p>Year: <%= @album.year %></p>
<p>Song Count: <%= @album.song_count %></p>
<%= link_to "Back", albums_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RockNRails</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= link_to "Make a New Album", new_album_path %>
    <%= yield %>
  </body>
</html>